### ISSUE TITLE
Update to latest package versions and dependencies

### ISSUE THREAD

**Issue by uliSchuster** [ClairBerlin/clair-admin-ui#45]
Use Vue 3 and the latest version of Quasar?

**Comment by rtzll** [comment]
Quasar is using Vue 2.
My understanding is that Quasar 2 will use Vue 3, but at the moment this is not compatible.

**Comment by uliSchuster** [comment]
> Quasar is using Vue 2.
> My understanding is that Quasar 2 will use Vue 3, but at the moment this is not compatible.

Thanks for the clarification. Then, there is not much to do here. It turns out that I incidentally updated the dependencies when I refreshed the `yarn.lock` file while extracting the expanded patchiest for `@reststate`.
